"""packages table + subscription tokens_used

Revision ID: 2458de6ee442
Revises: 8d43db0681c7
Create Date: 2026-07-11 16:42:44.064758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2458de6ee442'
down_revision: Union[str, None] = '8d43db0681c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_myr', sa.Integer(), nullable=False),
    sa.Column('monthly_token_quota', sa.Integer(), nullable=False),
    sa.Column('max_bots', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_id'), 'packages', ['id'], unique=False)
    op.create_index(op.f('ix_packages_slug'), 'packages', ['slug'], unique=True)
    # server_default backfills existing subscription rows to 0, then dropped so the
    # column matches the model (no DB default) and alembic check stays clean.
    op.add_column('subscriptions', sa.Column('tokens_used', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('subscriptions', 'tokens_used', server_default=None)

    # Seed the default sellable packages (operator edits these in the admin panel).
    packages = sa.table(
        'packages',
        sa.column('slug', sa.String), sa.column('name', sa.String),
        sa.column('price_myr', sa.Integer), sa.column('monthly_token_quota', sa.Integer),
        sa.column('max_bots', sa.Integer), sa.column('features', sa.JSON),
        sa.column('is_active', sa.Boolean), sa.column('sort_order', sa.Integer),
    )
    op.bulk_insert(packages, [
        {'slug': 'free', 'name': 'Free', 'price_myr': 0, 'monthly_token_quota': 20000, 'max_bots': 1,
         'features': ['1 chatbot', '~20k tokens / month', 'Website + WhatsApp', 'Email support'],
         'is_active': True, 'sort_order': 1},
        {'slug': 'starter', 'name': 'Starter', 'price_myr': 49, 'monthly_token_quota': 300000, 'max_bots': 3,
         'features': ['3 chatbots', '~300k tokens / month', 'Document + URL knowledge', 'Priority email support'],
         'is_active': True, 'sort_order': 2},
        {'slug': 'pro', 'name': 'Pro', 'price_myr': 149, 'monthly_token_quota': 1500000, 'max_bots': 10,
         'features': ['10 chatbots', '~1.5M tokens / month', 'All models incl. GPT/Claude', 'Analytics', 'Priority support'],
         'is_active': True, 'sort_order': 3},
        {'slug': 'business', 'name': 'Business', 'price_myr': 499, 'monthly_token_quota': 6000000, 'max_bots': 50,
         'features': ['50 chatbots', '~6M tokens / month', 'Everything in Pro', 'Dedicated onboarding'],
         'is_active': True, 'sort_order': 4},
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'tokens_used')
    op.drop_index(op.f('ix_packages_slug'), table_name='packages')
    op.drop_index(op.f('ix_packages_id'), table_name='packages')
    op.drop_table('packages')
    # ### end Alembic commands ###
