"""email_templates table

Revision ID: 7c318f1875c9
Revises: 2458de6ee442
Create Date: 2026-07-11 22:43:53.667133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c318f1875c9'
down_revision: Union[str, None] = '2458de6ee442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
    op.create_index(op.f('ix_email_templates_key'), 'email_templates', ['key'], unique=True)

    # Seed default transactional templates ({variable} placeholders, admin-editable).
    templates = sa.table(
        'email_templates',
        sa.column('key', sa.String), sa.column('name', sa.String),
        sa.column('subject', sa.String), sa.column('body_html', sa.Text),
        sa.column('is_active', sa.Boolean),
    )
    op.bulk_insert(templates, [
        {
            'key': 'welcome', 'name': 'Welcome', 'is_active': True,
            'subject': 'Welcome to AiTechSupport, {name}!',
            'body_html': (
                '<p>Hi {name},</p>'
                '<p>Your AiTechSupport account is ready. Add your knowledge, connect a channel, '
                'and your AI assistant can start answering customers.</p>'
                '<p><a href="{dashboard_url}">Open your dashboard</a></p>'
                '<p>— The AiTechSupport team</p>'
            ),
        },
        {
            'key': 'password_changed', 'name': 'Password changed', 'is_active': True,
            'subject': 'Your AiTechSupport password was changed',
            'body_html': (
                '<p>Hi {name},</p>'
                '<p>This is a confirmation that the password for {email} was just changed. '
                "If this wasn't you, please contact us immediately.</p>"
                '<p>— The AiTechSupport team</p>'
            ),
        },
        {
            'key': 'quota_warning', 'name': 'Token quota warning', 'is_active': True,
            'subject': "You've used most of your AiTechSupport tokens",
            'body_html': (
                '<p>Hi {name},</p>'
                '<p>Your <strong>{plan}</strong> plan is at {used_pct}% of its monthly token quota '
                '({tokens_remaining} left). Upgrade any time to avoid interruption.</p>'
                '<p><a href="{dashboard_url}">View plan &amp; usage</a></p>'
                '<p>— The AiTechSupport team</p>'
            ),
        },
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_templates_key'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_id'), table_name='email_templates')
    op.drop_table('email_templates')
    # ### end Alembic commands ###
